version: "3.8"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "${NGINX_PM_HTTP_PORT}:80"
      - "${NGINX_PM_HTTPS_PORT}:81"
      - "${NGINX_PM_PORT}:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt